### PR TITLE
Add new app: Get Kana

### PR DESCRIPTION
**Pull request by jairtrejo**
## Links
https://twitter.com/jairtrejo/status/700070525226209280

## Problem
**Get Kana!** is a mobile app for learning the Japanese syllabaries. You can get it in the app store, because apparently people prefer their apps packed in 20 MB of cruft and from a proprietary distribution channel, but it actually started its life as a PWA. I took great care to ensure it worked nicely in desktop and mobile, across platforms, and it's also [Open Source](https://github.com/jairtrejo/kana)!

I would love to add ["Get Kana!"](https://getkana.com/app) to the list of PWAs.

## Solution
It was using the old App Cache, I switched it to Service Workers [in this commit](https://github.com/jairtrejo/kana/commit/50b2a1e3e6faf96803b4ebd2adcd9276140f0cf7), it was very simple thanks to [sw-precache](https://github.com/GoogleChrome/sw-precache). I got a certificate and submitted a request to my hosting service to enable SSL, it should be done shortly.

Adding it to the list was straightforward. I changed the column-count to 4 because it looked really weird on 3, please let me know if I should change it.

Thanks for your consideration!

### CODE REVIEW

**Comment by pepelsbey** [comment]
Here’s updated version of the logo: responsive (always fits viewport) and compressed a bit. We’ll check how it works and get back to this PR shortly.

```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 900 900"><path d="M783,856.4C553.2,898.3,554,900,554,900l88.7-77.1Z" fill="#ec4d68"/><path d="M785.2,856.1L585,686,174.9,775.2ZM895.7,149.9L525.2,0l46.6,156.5Z" fill="#464040"/><path d="M0,154.6l897.1-4.8L900,707.1,175.8,775.4Z" fill="#ec4d68"/><path d="M162.68,482.94a412.1,412.1,0,0,1,69.53-31.62L243.68,380l68.3,2.57L301.69,437a172.93,172.93,0,0,1,19.05-1.16,77,77,0,0,1,40.37,10.47,79.05,79.05,0,0,1,29.78,29.56,117.82,117.82,0,0,1,14.19,40,142.15,142.15,0,0,1,1.34,41.74,233.05,233.05,0,0,1-26.15,80.92l-67.44-1.26a593,593,0,0,0,22.3-60.9,166.81,166.81,0,0,0,3.62-34.36,75.15,75.15,0,0,0-7.63-33.49C326,497.6,316.93,491.4,303.91,490a63.15,63.15,0,0,0-12,.36l-30,161.53-62-1.78,22-135.8c-13,6.31-25.65,13-37.89,20.08l-21.32-51.41m335.1-57.33-42.62,53.57q-32-35.84-66.83-68.23-33.79-30.81-66.87-62.4l39.72-46.41q29.82,23.73,58.37,48.6,39.88,36.59,78.23,74.87m6-73.81,72.73-9.69,9.6-57.75,57.16-1.69L635.32,334,680,328.23l0.52,59.31L627,394.32,608.54,555l-59.66,1,18.67-152.8-55,5.56-8.9-57m198.45,42,51.72-4.48c3.83,21.26,7.57,42.63,11.39,63.89a662.71,662.71,0,0,1,84.16,9.61L834.47,519c-20.78-5.17-41.6-9.83-62.64-13.76a270.16,270.16,0,0,1,2,36.13A61.21,61.21,0,0,1,757.45,581a62.27,62.27,0,0,1-37.2,20,87.79,87.79,0,0,1-31.88.52A63.2,63.2,0,0,1,659.6,589.7a61.23,61.23,0,0,1-19.93-24.15,98.17,98.17,0,0,1-8.57-30.26c-1.2-14.93,2.51-28.21,11.25-39.75A93,93,0,0,1,675,468.82a134.41,134.41,0,0,1,40.39-13.14c-4.16-20.62-8.61-41.21-13.28-62M762,289.66l52.75,20.41-40.77,73.35-48.33-17.8L762,289.76M725.35,534.61A315.8,315.8,0,0,0,722.53,501c-4.94.76-9.66,1.6-14.2,2.32a42.34,42.34,0,0,0-13.24,4.62,19.43,19.43,0,0,0-9.55,9.63,23.8,23.8,0,0,0-1.61,13.24,26.08,26.08,0,0,0,6,19.21c4.57,5.71,10.52,7.74,17.88,6.2a54.89,54.89,0,0,0,9.55-3.5,12.67,12.67,0,0,0,6.37-7.56,38.18,38.18,0,0,0,1.51-10.52" fill-opacity="0.2"/><path d="M147.71,468a412.1,412.1,0,0,1,69.53-31.62L228.7,365,297,367.6,286.72,422a172.93,172.93,0,0,1,19.05-1.16,77,77,0,0,1,40.37,10.47,79.05,79.05,0,0,1,29.78,29.56,117.82,117.82,0,0,1,14.19,40,142.15,142.15,0,0,1,1.34,41.74,233.05,233.05,0,0,1-26.15,80.92l-67.44-1.26a593,593,0,0,0,22.3-60.9A166.81,166.81,0,0,0,323.78,527a75.15,75.15,0,0,0-7.63-33.49C311,482.63,302,476.43,288.94,475a63.15,63.15,0,0,0-12,.36l-30,161.53-62-1.78,22-135.8c-13,6.31-25.65,13-37.89,20.08L147.71,468m335.1-57.33-42.62,53.57q-32-35.84-66.83-68.23-33.79-30.81-66.87-62.4l39.72-46.41q29.82,23.73,58.37,48.6,39.88,36.59,78.23,74.87m6-73.81,72.73-9.69,9.6-57.75,57.16-1.69L620.34,319,665,313.26l0.52,59.31L612,379.35,593.57,540.06l-59.66,1,18.67-152.8-55,5.56-8.9-57m198.45,42,51.72-4.48c3.83,21.26,7.57,42.63,11.39,63.89a662.71,662.71,0,0,1,84.16,9.61L819.5,504c-20.78-5.17-41.6-9.83-62.64-13.76a270.16,270.16,0,0,1,2,36.13A61.21,61.21,0,0,1,742.48,566a62.27,62.27,0,0,1-37.2,20,87.79,87.79,0,0,1-31.88.52,63.2,63.2,0,0,1-28.77-11.79,61.23,61.23,0,0,1-19.93-24.15,98.17,98.17,0,0,1-8.57-30.26c-1.2-14.93,2.51-28.21,11.25-39.75A93,93,0,0,1,660,453.85a134.41,134.41,0,0,1,40.39-13.14c-4.16-20.62-8.61-41.21-13.28-62M747,274.69l52.75,20.41L759,368.45l-48.33-17.8L747,274.79M710.38,519.64A315.8,315.8,0,0,0,707.56,486c-4.94.76-9.66,1.6-14.2,2.32a42.34,42.34,0,0,0-13.24,4.62,19.43,19.43,0,0,0-9.55,9.63A23.8,23.8,0,0,0,669,515.81,26.08,26.08,0,0,0,675,535c4.57,5.71,10.52,7.74,17.88,6.2a54.89,54.89,0,0,0,9.55-3.5,12.67,12.67,0,0,0,6.37-7.56,38.18,38.18,0,0,0,1.51-10.52" fill="#fef9fd"/></svg>
```

**Comment by mathiasbynens** [comment]
:+1:

**Comment by jairtrejo** [comment]
Awesome! I updated the logo.

**Comment by pepelsbey** [comment]
Thank you!

**Pull request merged**
