### PR TITLE
Removed busrouter, flipboard, trained to thrill, twitter

### PR DESCRIPTION
**Pull request by andreasbovens**

### CODE REVIEW

**Comment by pepelsbey** [comment]
@jakearchibald, do you think you can do anything to [Trained to Thrill](https://jakearchibald.github.io/trained-to-thrill/) app to make it more… progressive? So we could put it back. I beleive the problem is that it’s not triggering install banner in Opera or Chrome on Android, @andreasbovens could correct me if I’m wrong.

**Comment by cheeaun** [comment]
Just wondering, why is busrouter removed? 😢

**Comment by pepelsbey** [comment]
@cheeaun, as far as I remember it wasn’t triggering app install banner in Opera or Chrome for Android, but it’s better to ask @andreasbovens.

**Comment by cheeaun** [comment]
@andreasbovens would be great if you could advice 😁

**Comment by andreasbovens** [comment]
Yup, that was the problem indeed.

**Pull request merged**
