### PR TITLE
Add: Spotifinder PWA by Lee Boonstra

### PR DESCRIPTION
**Pull request by savelee**
Add: Spotifinder 
PWA by Lee Boonstra. Tool to retrieve LastFM music and play in Spotify.
Enter lastfm user name in settings screen. No lastfm account? For demo, use mine: "savelee"

Progressive Web App. Open on desktop vs mobile for universal app experience.

### CODE REVIEW

**Comment by pepelsbey** [comment]
Do you have a source of this icon? We use SVG for icons and I could probably redraw it in vector, but it’s better to use existing artwork.

**Comment by savelee** [comment]
Nope, unfortunately I don't. - I thought the other icons where somehow exported as SVGs...
Thanks anyways.

**Comment by savelee** [comment]
I've created an SVG image of the artwork.. thanks!

**Comment by savelee** [comment]
Is there anything left to do for me, to get this merged?
I like to see this app listed, since this is a great example of the Sencha Ext JS framework as PWA.
Thanks!

**Comment by pepelsbey** [comment]
Sorry, it’s just a matter of free time to test it and merge. Will finish it by the end of the day.

**Comment by savelee** [comment]
Great! Let me know if you need anything!

**Comment by savelee** [comment]
Bumping this one up... -  Is there anything I can do, to help you? To get this one live?

Thanks!

**Comment by pepelsbey** [comment]
Sorry, we’ve discussed Spotifinder a bit more and decided that it’s not the best web application to promote PWA: different UI for different platform, empty list with an alert that something’s wrong on mobile, etc. I’m really sorry for wasting your time with icon and the whole PR.

**Pull request closed without merging**
